---

services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.6.13 
    container_name: adguardhome-sync
    command: run
    environment:
      ORIGIN_URL: ${ORIGIN_URL}
      ORIGIN_USERNAME: ${ORIGIN_USERNAME}
      ORIGIN_PASSWORD: ${ORIGIN_PASSWORD}
      
      REPLICA1_URL: ${REPLICA1_URL}
      REPLICA1_USERNAME: ${REPLICA1_USERNAME}
      REPLICA1_PASSWORD: ${REPLICA1_PASSWORD}
      
      CRON: "*/10 * * * *" # run every 10 minutes
      LOG_LEVEL: "info"
      RUN_ON_START: true
      API_PORT: 8080
    ports:
      - 8081:8080
    restart: unless-stopped