---

services:
  adguard-home:
    image: 'adguard/adguardhome:v0.107.53'
    container_name: 'adguard-home'
    restart: 'unless-stopped'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/docker/adguard-home/appdata/work:/opt/adguardhome/work'
      - '/opt/docker/adguard-home/appdata/config:/opt/adguardhome/conf'
    ports:
      # Plain DNS
      - '53:53/tcp'
      - '53:53/udp'
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - '81:80/tcp'
      # - '443:443/tcp'
      # - '443:443/udp'
      - '3000:3000/tcp'
      # DNS-over-TLS
      # - '853:853/tcp'
      # DNS-over-QUIC
      # - '784:784/udp'
      # - '853:853/udp'
      # - '8853:8853/udp'
      # DNSCrypt
      # - '5443:5443/tcp'
      # - '5443:5443/udp'